// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonApp.Models;

namespace PokemonApp.Migrations
{
    [DbContext(typeof(PokemonDBContext))]
    partial class PokemonDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonApp.Models.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OtherUser")
                        .HasColumnType("int")
                        .HasColumnName("other_user");

                    b.Property<int>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.HasIndex("OtherUser");

                    b.HasIndex("User");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("PokemonApp.Models.Highscore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<int>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.Property<int?>("Victories")
                        .HasColumnType("int")
                        .HasColumnName("victories");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("Highscores");
                });

            modelBuilder.Entity("PokemonApp.Models.PokemonCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PokemonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pokemon_id");

                    b.Property<int>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.HasIndex("User");

                    b.ToTable("PokemonCards");
                });

            modelBuilder.Entity("PokemonApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cash")
                        .HasColumnType("int")
                        .HasColumnName("cash");

                    b.Property<DateTime?>("Freeclick")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<int?>("Xp")
                        .HasColumnType("int")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PokemonApp.Models.Connection", b =>
                {
                    b.HasOne("PokemonApp.Models.User", "OtherUserNavigation")
                        .WithMany("ConnectionOtherUserNavigations")
                        .HasForeignKey("OtherUser")
                        .HasConstraintName("FK_Connections_User1")
                        .IsRequired();

                    b.HasOne("PokemonApp.Models.User", "UserNavigation")
                        .WithMany("ConnectionUserNavigations")
                        .HasForeignKey("User")
                        .HasConstraintName("FK_Connections_User")
                        .IsRequired();

                    b.Navigation("OtherUserNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("PokemonApp.Models.Highscore", b =>
                {
                    b.HasOne("PokemonApp.Models.User", "UserNavigation")
                        .WithMany("Highscores")
                        .HasForeignKey("User")
                        .HasConstraintName("FK_Highscores_User")
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("PokemonApp.Models.PokemonCard", b =>
                {
                    b.HasOne("PokemonApp.Models.User", "UserNavigation")
                        .WithMany("PokemonCards")
                        .HasForeignKey("User")
                        .HasConstraintName("FK_PokemonCards_User")
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("PokemonApp.Models.User", b =>
                {
                    b.Navigation("ConnectionOtherUserNavigations");

                    b.Navigation("ConnectionUserNavigations");

                    b.Navigation("Highscores");

                    b.Navigation("PokemonCards");
                });
#pragma warning restore 612, 618
        }
    }
}
